name: Update project

on:
  push:
    branches: [ "master" ]
    paths: [ ".github/" ]
  schedule: 
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        type: string

env:
  PROJECT_URL: "https://scratch.mit.edu/projects/510186917/"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup Node
        uses: actions/setup-node@v3.4.1
        
      - id: install
        name: Install SBDL
        run: npm install --global @turbowarp/sbdl

      - id: download 
        name: Download SB3
        run: sbdl  
        
  push:
    needs: fetch
    runs-on: ubuntu-latest
  release:
    needs: push
    if: "${{ github.event.inputs.version != '' }}"
    runs-on: ubuntu-latest
